POST http://localhost:5000/api/register
Content-Type: application/json

{
    "username": "yhzx233",
    "password": "1919810",
    "email": "114514@qq.com"
}

###
POST http://localhost:5000/api/login
content-type: application/json

{
    "username": "yhzx233",
    "password": "1919810"
}

###

GET http://localhost:5000/api/user

###

GET http://localhost:5000/api/logout

###

PUT http://localhost:5000/api/user
Content-Type: application/json

{
    "username": "yhzx6666",
    "email": "2058777361@qq.com"
}